---
- name: install beanstalkd packages
  yum: pkg={{ item }} state=latest
  with_items:
    - beanstalkd

- name: setup service
  template: src=redhat-beanstalkd.j2 dest=/etc/sysconfig/beanstalkd mode=0755
  notify: restart beanstalkd